export enum BET_STATUS {
  INIT = 'INIT',
  CONFIRMED = 'CONFIRMED',
  WIN = 'WIN',
  LOSE = 'LOSE',
  REJECT = 'REJECT',
}

export enum ODDS_CODE {
  HOME = 'HOME',
  AWAY = 'AWAY',
  DRAW = 'DRAW',
}

export enum MATCH_TYPE {
  GROUP_STAGE = 'GROUP STAGE',
  ROUND_OF_16 = 'ROUND OF 16',
  QUARTER = 'QUARTER',
  SEMI_FINAL = 'SEMI FINAL',
  FINAL = 'FINAL',
}

export enum RANGE_TIME {
  TODAY = 'TODAY',
  TOMORROW = 'TOMORROW',
  THIS_WEEK = 'THIS WEEK',
  CUSTOM = 'CUSTOM',
}
